allowBuilds:
  '@parcel/watcher': set this to true or false
  deasync: set this to true or false
  esbuild: set this to true or false
  less: set this to true or false
  sharp: set this to true or false
  vercel: set this to true or false
